// <auto-generated />
using System;
using DnnMigration.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnnMigration.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DnnDbContext))]
    [Migration("20260101000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DnnMigration.Domain.Entities.DesktopModule", b =>
                {
                    b.Property<int>("DesktopModuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DesktopModuleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesktopModuleID"));

                    b.Property<string>("BusinessControllerClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BusinessControllerClass");

                    b.Property<string>("CompatibleVersions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompatibleVersions");

                    b.Property<string>("Dependencies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Dependencies");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FolderName");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FriendlyName");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("IsAdmin");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit")
                        .HasColumnName("IsPremium");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModuleName");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Permissions");

                    b.Property<int>("SupportedFeatures")
                        .HasColumnType("int")
                        .HasColumnName("SupportedFeatures");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Version");

                    b.HasKey("DesktopModuleID");

                    b.HasIndex("FriendlyName")
                        .IsUnique()
                        .HasDatabaseName("IX_DesktopModules");

                    b.ToTable("DesktopModules", (string)null);
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.FolderPermission", b =>
                {
                    b.Property<int>("FolderPermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FolderPermissionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FolderPermissionID"));

                    b.Property<bool>("AllowAccess")
                        .HasColumnType("bit")
                        .HasColumnName("AllowAccess");

                    b.Property<int>("FolderID")
                        .HasColumnType("int")
                        .HasColumnName("FolderID");

                    b.Property<int>("PermissionID")
                        .HasColumnType("int")
                        .HasColumnName("PermissionID");

                    b.Property<int>("RoleID")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("FolderPermissionID");

                    b.HasIndex("PermissionID");

                    b.ToTable("FolderPermission", (string)null);
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Module", b =>
                {
                    b.Property<int>("ModuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleID"));

                    b.Property<string>("Alignment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Alignment");

                    b.Property<bool>("AllTabs")
                        .HasColumnType("bit")
                        .HasColumnName("AllTabs");

                    b.Property<string>("AuthorizedEditRoles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AuthorizedEditRoles");

                    b.Property<string>("AuthorizedViewRoles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AuthorizedViewRoles");

                    b.Property<string>("Border")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Border");

                    b.Property<int>("CacheTime")
                        .HasColumnType("int")
                        .HasColumnName("CacheTime");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Color");

                    b.Property<string>("ContainerSrc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContainerSrc");

                    b.Property<int>("ControlType")
                        .HasColumnType("int")
                        .HasColumnName("ControlType");

                    b.Property<bool>("DisplayPrint")
                        .HasColumnType("bit")
                        .HasColumnName("DisplayPrint");

                    b.Property<bool>("DisplaySyndicate")
                        .HasColumnType("bit")
                        .HasColumnName("DisplaySyndicate");

                    b.Property<bool>("DisplayTitle")
                        .HasColumnType("bit")
                        .HasColumnName("DisplayTitle");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<string>("Footer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Footer");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Header");

                    b.Property<string>("IconFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IconFile");

                    b.Property<bool>("InheritViewPermissions")
                        .HasColumnType("bit")
                        .HasColumnName("InheritViewPermissions");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int>("ModuleDefID")
                        .HasColumnType("int")
                        .HasColumnName("ModuleDefID");

                    b.Property<int>("ModuleOrder")
                        .HasColumnType("int")
                        .HasColumnName("ModuleOrder");

                    b.Property<string>("ModuleTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModuleTitle");

                    b.Property<string>("PaneName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PaneName");

                    b.Property<int>("PortalID")
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<int>("TabID")
                        .HasColumnType("int")
                        .HasColumnName("TabID");

                    b.Property<int>("TabModuleID")
                        .HasColumnType("int")
                        .HasColumnName("TabModuleID");

                    b.Property<int>("Visibility")
                        .HasColumnType("int")
                        .HasColumnName("Visibility");

                    b.HasKey("ModuleID");

                    b.ToTable("Modules", (string)null);
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.ModuleDefinition", b =>
                {
                    b.Property<int>("ModuleDefID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModuleDefID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleDefID"));

                    b.Property<int>("DefaultCacheTime")
                        .HasColumnType("int")
                        .HasColumnName("DefaultCacheTime");

                    b.Property<int>("DesktopModuleID")
                        .HasColumnType("int")
                        .HasColumnName("DesktopModuleID");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FriendlyName");

                    b.HasKey("ModuleDefID");

                    b.ToTable("ModuleDefinitions", (string)null);
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.ModulePermission", b =>
                {
                    b.Property<int>("ModulePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModulePermissionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModulePermissionID"));

                    b.Property<bool>("AllowAccess")
                        .HasColumnType("bit")
                        .HasColumnName("AllowAccess");

                    b.Property<int>("ModuleID")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<int>("PermissionID")
                        .HasColumnType("int")
                        .HasColumnName("PermissionID");

                    b.Property<int>("RoleID")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("ModulePermissionID");

                    b.HasIndex("ModuleID");

                    b.HasIndex("PermissionID");

                    b.ToTable("ModulePermission", (string)null);
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PermissionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionID"));

                    b.Property<int>("ModuleDefID")
                        .HasColumnType("int")
                        .HasColumnName("ModuleDefID");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PermissionCode");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PermissionKey");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PermissionName");

                    b.HasKey("PermissionID");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Portal", b =>
                {
                    b.Property<int>("PortalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortalID"));

                    b.Property<int>("AdminTabId")
                        .HasColumnType("int")
                        .HasColumnName("AdminTabId");

                    b.Property<int>("AdministratorId")
                        .HasColumnType("int")
                        .HasColumnName("AdministratorId");

                    b.Property<int>("AdministratorRoleId")
                        .HasColumnType("int")
                        .HasColumnName("AdministratorRoleId");

                    b.Property<string>("BackgroundFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BackgroundFile");

                    b.Property<int>("BannerAdvertising")
                        .HasColumnType("int")
                        .HasColumnName("BannerAdvertising");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Currency");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DefaultLanguage");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiryDate");

                    b.Property<string>("FooterText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FooterText");

                    b.Property<Guid>("GUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID");

                    b.Property<string>("HomeDirectory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HomeDirectory");

                    b.Property<int>("HomeTabId")
                        .HasColumnType("int")
                        .HasColumnName("HomeTabId");

                    b.Property<float>("HostFee")
                        .HasColumnType("real")
                        .HasColumnName("HostFee");

                    b.Property<int>("HostSpace")
                        .HasColumnType("int")
                        .HasColumnName("HostSpace");

                    b.Property<string>("KeyWords")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KeyWords");

                    b.Property<int>("LoginTabId")
                        .HasColumnType("int")
                        .HasColumnName("LoginTabId");

                    b.Property<string>("LogoFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LogoFile");

                    b.Property<int>("PageQuota")
                        .HasColumnType("int")
                        .HasColumnName("PageQuota");

                    b.Property<string>("PaymentProcessor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PaymentProcessor");

                    b.Property<string>("PortalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PortalName");

                    b.Property<string>("ProcessorPassword")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProcessorPassword");

                    b.Property<string>("ProcessorUserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProcessorUserId");

                    b.Property<int>("RegisteredRoleId")
                        .HasColumnType("int")
                        .HasColumnName("RegisteredRoleId");

                    b.Property<int>("SiteLogHistory")
                        .HasColumnType("int")
                        .HasColumnName("SiteLogHistory");

                    b.Property<int>("SplashTabId")
                        .HasColumnType("int")
                        .HasColumnName("SplashTabId");

                    b.Property<int>("TimeZoneOffset")
                        .HasColumnType("int")
                        .HasColumnName("TimezoneOffset");

                    b.Property<int>("UserQuota")
                        .HasColumnType("int")
                        .HasColumnName("UserQuota");

                    b.Property<int>("UserRegistration")
                        .HasColumnType("int")
                        .HasColumnName("UserRegistration");

                    b.Property<int>("UserTabId")
                        .HasColumnType("int")
                        .HasColumnName("UserTabId");

                    b.HasKey("PortalID");

                    b.ToTable("Portals", (string)null);
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.PortalAlias", b =>
                {
                    b.Property<int>("PortalAliasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PortalAliasID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortalAliasID"));

                    b.Property<string>("HTTPAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HTTPAlias");

                    b.Property<int>("PortalID")
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    b.HasKey("PortalAliasID");

                    b.HasIndex("PortalID");

                    b.ToTable("PortalAlias", (string)null);
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<bool>("AutoAssignment")
                        .HasColumnType("bit")
                        .HasColumnName("AutoAssignment");

                    b.Property<string>("BillingFrequency")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BillingFrequency");

                    b.Property<int>("BillingPeriod")
                        .HasColumnType("int")
                        .HasColumnName("BillingPeriod");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("IconFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IconFile");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit")
                        .HasColumnName("IsPublic");

                    b.Property<int>("PortalID")
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    b.Property<string>("RSVPCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RSVPCode");

                    b.Property<int>("RoleGroupID")
                        .HasColumnType("int")
                        .HasColumnName("RoleGroupID");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RoleName");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("money")
                        .HasColumnName("ServiceFee");

                    b.Property<decimal>("TrialFee")
                        .HasColumnType("money")
                        .HasColumnName("TrialFee");

                    b.Property<string>("TrialFrequency")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrialFrequency");

                    b.Property<int>("TrialPeriod")
                        .HasColumnType("int")
                        .HasColumnName("TrialPeriod");

                    b.HasKey("RoleID");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Tab", b =>
                {
                    b.Property<int>("TabID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TabID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TabID"));

                    b.Property<string>("ContainerSrc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContainerSrc");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<bool>("DisableLink")
                        .HasColumnType("bit")
                        .HasColumnName("DisableLink");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<string>("IconFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IconFile");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsSecure")
                        .HasColumnType("bit")
                        .HasColumnName("IsSecure");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnName("IsVisible");

                    b.Property<string>("KeyWords")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KeyWords");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("Level");

                    b.Property<string>("PageHeadText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PageHeadText");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentId");

                    b.Property<int>("PortalID")
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    b.Property<int>("RefreshInterval")
                        .HasColumnType("int")
                        .HasColumnName("RefreshInterval");

                    b.Property<string>("SkinSrc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SkinSrc");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<string>("TabName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TabName");

                    b.Property<int>("TabOrder")
                        .HasColumnType("int")
                        .HasColumnName("TabOrder");

                    b.Property<string>("TabPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TabPath");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Url");

                    b.HasKey("TabID");

                    b.ToTable("Tabs", (string)null);
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.TabPermission", b =>
                {
                    b.Property<int>("TabPermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TabPermissionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TabPermissionID"));

                    b.Property<bool>("AllowAccess")
                        .HasColumnType("bit")
                        .HasColumnName("AllowAccess");

                    b.Property<int>("PermissionID")
                        .HasColumnType("int")
                        .HasColumnName("PermissionID");

                    b.Property<int>("RoleID")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int>("TabID")
                        .HasColumnType("int")
                        .HasColumnName("TabID");

                    b.HasKey("TabPermissionID");

                    b.HasIndex("PermissionID");

                    b.HasIndex("TabID");

                    b.ToTable("TabPermission", (string)null);
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("AffiliateID")
                        .HasColumnType("int")
                        .HasColumnName("AffiliateId");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsSuperUser")
                        .HasColumnType("bit")
                        .HasColumnName("IsSuperUser");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastName");

                    b.Property<int>("PortalID")
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Username");

                    b.HasKey("UserID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUpdatedDate");

                    b.Property<string>("PropertyNames")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PropertyNames");

                    b.Property<byte[]>("PropertyValuesBinary")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PropertyValuesBinary");

                    b.Property<string>("PropertyValuesString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PropertyValuesString");

                    b.HasKey("UserId");

                    b.ToTable("aspnet_Profile", (string)null);
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.FolderPermission", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FolderPermission_Permission");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.ModulePermission", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.Module", null)
                        .WithMany("ModulePermissions")
                        .HasForeignKey("ModuleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ModulePermission_Modules");

                    b.HasOne("DnnMigration.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ModulePermission_Permission");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.PortalAlias", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.Portal", null)
                        .WithMany()
                        .HasForeignKey("PortalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PortalAlias_Portals");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.TabPermission", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TabPermission_Permission");

                    b.HasOne("DnnMigration.Domain.Entities.Tab", null)
                        .WithMany("TabPermissions")
                        .HasForeignKey("TabID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TabPermission_Tabs");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.User", b =>
                {
                    b.OwnsOne("DnnMigration.Domain.Entities.UserMembership", "Membership", b1 =>
                        {
                            b1.Property<int>("UserID")
                                .HasColumnType("int");

                            b1.Property<bool>("Approved")
                                .HasColumnType("bit")
                                .HasColumnName("IsApproved");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreateDate");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Email");

                            b1.Property<DateTime>("LastLockoutDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("LastLockoutDate");

                            b1.Property<DateTime>("LastLoginDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("LastLoginDate");

                            b1.Property<DateTime>("LastPasswordChangeDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("LastPasswordChangedDate");

                            b1.Property<bool>("LockedOut")
                                .HasColumnType("bit")
                                .HasColumnName("IsLockedOut");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Password");

                            b1.Property<string>("PasswordAnswer")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PasswordAnswer");

                            b1.Property<string>("PasswordQuestion")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PasswordQuestion");

                            b1.HasKey("UserID");

                            b1.ToTable("aspnet_Membership", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserID");
                        });

                    b.Navigation("Membership")
                        .IsRequired();
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Module", b =>
                {
                    b.Navigation("ModulePermissions");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Tab", b =>
                {
                    b.Navigation("TabPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
