namespace DnnMigration.Application.DTOs;

/// <summary>
/// Request payload used to create a new role.
/// </summary>
/// <remarks>
/// MIGRATION: mirrors the editable field set of the legacy role-edit screen
/// (<c>Website/admin/Security/editroles.ascx</c>) projected over the DotNetNuke
/// <c>RoleInfo</c> entity (<c>Library/Components/Security/Roles/RoleInfo.vb</c>).
/// This immutable request record is bound from the body of <c>POST /api/roles</c>,
/// validated by the sibling FluentValidation validator, and mapped onto the
/// <c>Role</c> domain entity via AutoMapper - controllers never bind directly to
/// entities.
/// <para>
/// MIGRATION: the identity field <c>RoleID</c> present on <c>RoleInfo</c> is
/// intentionally omitted here because the identifier is generated by the
/// persistence layer on insert; a create request must not carry it.
/// </para>
/// <para>
/// MIGRATION: the VB.NET <c>Single</c> fee fields (<c>ServiceFee</c>,
/// <c>TrialFee</c>) are mirrored as <see cref="float"/> to preserve the original
/// numeric width rather than widening to <see cref="double"/>, keeping behavioral
/// equivalence with the legacy model.
/// </para>
/// </remarks>
public record CreateRoleDto
{
    /// <summary>
    /// Identifier of the portal that owns the role.
    /// </summary>
    public int PortalID { get; init; }

    /// <summary>
    /// Identifier of the role group this role belongs to.
    /// </summary>
    public int RoleGroupID { get; init; }

    /// <summary>
    /// Display name of the role. Defaults to <see cref="string.Empty"/> so the
    /// non-nullable property always has a safe value during model binding.
    /// </summary>
    public string RoleName { get; init; } = string.Empty;

    /// <summary>
    /// Optional free-text description of the role.
    /// </summary>
    public string? Description { get; init; }

    /// <summary>
    /// Indicates whether the role is publicly visible and self-subscribable.
    /// </summary>
    public bool IsPublic { get; init; }

    /// <summary>
    /// Indicates whether new users are automatically assigned to the role.
    /// </summary>
    public bool AutoAssignment { get; init; }

    /// <summary>
    /// Recurring service fee charged for membership in the role.
    /// </summary>
    public float ServiceFee { get; init; }

    /// <summary>
    /// Billing frequency code for the service fee. Legacy code values:
    /// <c>N</c> (none), <c>O</c> (one-time), <c>D</c> (daily), <c>W</c> (weekly),
    /// <c>M</c> (monthly) or <c>Y</c> (yearly).
    /// </summary>
    public string? BillingFrequency { get; init; }

    /// <summary>
    /// Length of the billing period, expressed in <see cref="BillingFrequency"/> units.
    /// </summary>
    public int BillingPeriod { get; init; }

    /// <summary>
    /// Fee charged for the trial period.
    /// </summary>
    public float TrialFee { get; init; }

    /// <summary>
    /// Length of the trial period, expressed in <see cref="TrialFrequency"/> units.
    /// </summary>
    public int TrialPeriod { get; init; }

    /// <summary>
    /// Trial frequency code for the trial fee. Legacy code values:
    /// <c>N</c> (none), <c>O</c> (one-time), <c>D</c> (daily), <c>W</c> (weekly),
    /// <c>M</c> (monthly) or <c>Y</c> (yearly).
    /// </summary>
    public string? TrialFrequency { get; init; }

    /// <summary>
    /// Optional RSVP code required to join the role.
    /// </summary>
    public string? RSVPCode { get; init; }

    /// <summary>
    /// Optional relative path to the icon file associated with the role.
    /// </summary>
    public string? IconFile { get; init; }
}
