/**
 * Base HTTP Service for DNN Migration Portal
 * Angular 19 SPA - Core API Communication Service
 *
 * MIGRATION NOTE: This service replaces the legacy DotNetNuke 4.x SqlDataProvider
 * data access patterns with modern Angular HttpClient Observable patterns.
 *
 * Legacy Pattern Mapping:
 * - SqlHelper.ExecuteReader() → HttpClient.get() with Observable<T>
 * - SqlHelper.ExecuteNonQuery() → HttpClient.post()/put()/delete()
 * - SqlHelper.ExecuteScalar() → HttpClient.get() with typed response
 * - Config.GetConnectionString() → environment.apiBaseUrl configuration
 * - Try-catch error handling → RxJS catchError operator
 *
 * @see SqlDataProvider.vb lines 40-70 for original patterns
 * @see Section 0.7.6 Error Handling Standards for RFC 7807 compliance
 */

import { Injectable, inject } from '@angular/core';
import { HttpClient, HttpParams, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { catchError } from 'rxjs/operators';

import { environment } from '../../../environments/environment';

/**
 * RFC 7807 Problem Details for HTTP APIs
 *
 * This interface implements the standard error response format as specified
 * in RFC 7807 (Problem Details for HTTP APIs). All API error responses from
 * the ASP.NET Core backend conform to this structure.
 *
 * MIGRATION NOTE: This replaces the legacy DNN exception handling pattern
 * where errors were typically caught with Try-Catch and logged via
 * DNN's EventLog. The reactive error handling approach propagates errors
 * through the Observable stream for centralized handling.
 *
 * @see https://www.rfc-editor.org/rfc/rfc7807
 * @see Section 0.7.6 Error Handling Standards
 */
export interface ApiError {
  /**
   * A URI reference that identifies the problem type.
   * Example: "https://dnnmigration.com/errors/validation"
   */
  type: string;

  /**
   * A short, human-readable summary of the problem type.
   * Example: "Validation Error"
   */
  title: string;

  /**
   * The HTTP status code generated by the origin server for this occurrence.
   * Example: 400, 401, 403, 404, 500
   */
  status: number;

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   * Example: "One or more validation errors occurred."
   */
  detail: string;

  /**
   * Optional field-specific validation errors.
   * Keys are field names, values are arrays of error messages.
   * Example: { "portalName": ["Portal name is required.", "Portal name must be at least 3 characters."] }
   *
   * MIGRATION NOTE: This maps to the legacy DNN validation patterns where
   * individual field errors were typically shown via lblError labels or
   * validation summary controls.
   */
  errors?: Record<string, string[]>;
}

/**
 * Base HTTP Service for Angular 19 SPA
 *
 * Provides centralized API communication with the ASP.NET Core backend.
 * Implements singleton pattern via providedIn: 'root' for application-wide
 * instance sharing.
 *
 * Features:
 * - Generic HTTP methods with typed responses (get<T>, post<T>, put<T>, delete)
 * - Centralized error handling with RFC 7807 ApiError transformation
 * - Environment-based URL configuration
 * - Observable-based response patterns using RxJS
 *
 * MIGRATION NOTE: This service serves as the foundation for all feature-specific
 * services (PortalService, UserService, ModuleService, RoleService), replacing
 * the legacy DNN data provider pattern where each controller directly called
 * SqlHelper methods.
 *
 * Legacy DNN Pattern:
 * ```vb
 * ' From SqlDataProvider.vb
 * Private _connectionString As String
 * _connectionString = Config.GetConnectionString()
 * SqlHelper.ExecuteReader(ConnectionString, ...)
 * ```
 *
 * Modern Angular Pattern:
 * ```typescript
 * private apiUrl = environment.apiBaseUrl;
 * this.http.get<T>(this.buildUrl(endpoint))
 * ```
 *
 * @example
 * ```typescript
 * // In a feature service
 * export class PortalService {
 *   private api = inject(ApiService);
 *
 *   getPortal(id: number): Observable<Portal> {
 *     return this.api.get<Portal>(`portals/${id}`);
 *   }
 *
 *   createPortal(data: CreatePortalRequest): Observable<Portal> {
 *     return this.api.post<Portal>('portals', data);
 *   }
 * }
 * ```
 */
@Injectable({
  providedIn: 'root'
})
export class ApiService {
  /**
   * Angular HttpClient instance injected via inject() function.
   * MIGRATION NOTE: Uses Angular 19 inject() function pattern instead of
   * constructor injection for cleaner, more concise service definitions.
   */
  private readonly http = inject(HttpClient);

  /**
   * Base URL for all API requests.
   * MIGRATION NOTE: Reads from environment configuration, replacing the
   * legacy DNN Config.GetConnectionString() pattern.
   *
   * Development: 'http://localhost:5000/api'
   * Production: Configured via environment.prod.ts
   */
  private readonly apiUrl: string = environment.apiBaseUrl;

  /**
   * Default HTTP headers for JSON API requests.
   * Applied to POST and PUT requests automatically.
   */
  private readonly defaultHeaders = new HttpHeaders({
    'Content-Type': 'application/json',
    'Accept': 'application/json'
  });

  /**
   * Performs an HTTP GET request with optional query parameters.
   *
   * MIGRATION NOTE: Replaces SqlHelper.ExecuteReader() pattern:
   * ```vb
   * ' Legacy VB.NET
   * Dim dr As IDataReader = SqlHelper.ExecuteReader(ConnectionString, _
   *   DatabaseOwner & ObjectQualifier & "GetPortal", PortalId)
   * ```
   *
   * @template T - Expected response type
   * @param endpoint - API endpoint path (without base URL). Example: 'portals', 'users/123'
   * @param params - Optional HttpParams for query string parameters (filtering, pagination, etc.)
   * @returns Observable<T> - Observable emitting the typed response or error
   *
   * @example
   * ```typescript
   * // Simple GET
   * this.api.get<Portal[]>('portals').subscribe(portals => { ... });
   *
   * // GET with query parameters
   * const params = new HttpParams()
   *   .set('pageIndex', '0')
   *   .set('pageSize', '10')
   *   .set('filter', 'active');
   * this.api.get<PagedResult<Portal>>('portals', params).subscribe(result => { ... });
   * ```
   */
  get<T>(endpoint: string, params?: HttpParams): Observable<T> {
    const url = this.buildUrl(endpoint);
    const options = params ? { params } : {};

    return this.http.get<T>(url, options).pipe(
      catchError((error: HttpErrorResponse) => this.handleError(error))
    );
  }

  /**
   * Performs an HTTP POST request to create a new resource.
   *
   * MIGRATION NOTE: Replaces SqlHelper.ExecuteNonQuery() pattern for insert operations:
   * ```vb
   * ' Legacy VB.NET
   * SqlHelper.ExecuteNonQuery(ConnectionString, DatabaseOwner & ObjectQualifier & "AddPortal", _
   *   PortalName, ExpiryDate, UserRegistration, ...)
   * ```
   *
   * @template T - Expected response type
   * @param endpoint - API endpoint path (without base URL). Example: 'portals', 'users'
   * @param body - Request body to send (will be serialized as JSON)
   * @returns Observable<T> - Observable emitting the created resource or error
   *
   * @example
   * ```typescript
   * const newPortal: CreatePortalRequest = {
   *   portalName: 'My Portal',
   *   description: 'A new portal'
   * };
   * this.api.post<Portal>('portals', newPortal).subscribe(created => { ... });
   * ```
   */
  post<T>(endpoint: string, body: unknown): Observable<T> {
    const url = this.buildUrl(endpoint);

    return this.http.post<T>(url, body, { headers: this.defaultHeaders }).pipe(
      catchError((error: HttpErrorResponse) => this.handleError(error))
    );
  }

  /**
   * Performs an HTTP PUT request to update an existing resource.
   *
   * MIGRATION NOTE: Replaces SqlHelper.ExecuteNonQuery() pattern for update operations:
   * ```vb
   * ' Legacy VB.NET
   * SqlHelper.ExecuteNonQuery(ConnectionString, DatabaseOwner & ObjectQualifier & "UpdatePortal", _
   *   PortalId, PortalName, ExpiryDate, ...)
   * ```
   *
   * @template T - Expected response type
   * @param endpoint - API endpoint path (without base URL). Example: 'portals/123'
   * @param body - Request body with updated data (will be serialized as JSON)
   * @returns Observable<T> - Observable emitting the updated resource or error
   *
   * @example
   * ```typescript
   * const update: UpdatePortalRequest = {
   *   portalName: 'Updated Portal Name',
   *   description: 'Updated description'
   * };
   * this.api.put<Portal>('portals/123', update).subscribe(updated => { ... });
   * ```
   */
  put<T>(endpoint: string, body: unknown): Observable<T> {
    const url = this.buildUrl(endpoint);

    return this.http.put<T>(url, body, { headers: this.defaultHeaders }).pipe(
      catchError((error: HttpErrorResponse) => this.handleError(error))
    );
  }

  /**
   * Performs an HTTP DELETE request to remove a resource.
   *
   * MIGRATION NOTE: Replaces SqlHelper.ExecuteNonQuery() pattern for delete operations:
   * ```vb
   * ' Legacy VB.NET
   * SqlHelper.ExecuteNonQuery(ConnectionString, DatabaseOwner & ObjectQualifier & "DeletePortal", _
   *   PortalId)
   * ```
   *
   * @param endpoint - API endpoint path (without base URL). Example: 'portals/123'
   * @returns Observable<void> - Observable completing on success or emitting error
   *
   * @example
   * ```typescript
   * this.api.delete('portals/123').subscribe({
   *   complete: () => console.log('Portal deleted'),
   *   error: (err) => console.error('Delete failed', err)
   * });
   * ```
   */
  delete(endpoint: string): Observable<void> {
    const url = this.buildUrl(endpoint);

    return this.http.delete<void>(url).pipe(
      catchError((error: HttpErrorResponse) => this.handleError(error))
    );
  }

  /**
   * Performs an HTTP PATCH request for partial resource updates.
   *
   * @template T - Expected response type
   * @param endpoint - API endpoint path (without base URL)
   * @param body - Partial update data (will be serialized as JSON)
   * @returns Observable<T> - Observable emitting the patched resource or error
   *
   * @example
   * ```typescript
   * this.api.patch<Portal>('portals/123', { isActive: false }).subscribe(patched => { ... });
   * ```
   */
  patch<T>(endpoint: string, body: unknown): Observable<T> {
    const url = this.buildUrl(endpoint);

    return this.http.patch<T>(url, body, { headers: this.defaultHeaders }).pipe(
      catchError((error: HttpErrorResponse) => this.handleError(error))
    );
  }

  /**
   * Builds the complete URL by combining the base API URL with the endpoint path.
   *
   * MIGRATION NOTE: This replaces the DNN pattern of constructing qualified
   * stored procedure names:
   * ```vb
   * ' Legacy VB.NET
   * Private _databaseOwner As String
   * Private _objectQualifier As String
   * DatabaseOwner & ObjectQualifier & "GetPortal"
   * ```
   *
   * @param endpoint - Relative API endpoint path
   * @returns Complete URL string for the API request
   *
   * @example
   * ```typescript
   * this.buildUrl('portals')     // => 'http://localhost:5000/api/portals'
   * this.buildUrl('users/123')   // => 'http://localhost:5000/api/users/123'
   * ```
   */
  private buildUrl(endpoint: string): string {
    // Ensure no double slashes when concatenating
    const baseUrl = this.apiUrl.endsWith('/') ? this.apiUrl.slice(0, -1) : this.apiUrl;
    const path = endpoint.startsWith('/') ? endpoint.slice(1) : endpoint;

    return `${baseUrl}/${path}`;
  }

  /**
   * Centralized error handler for all HTTP requests.
   *
   * Transforms HttpErrorResponse into a standardized ApiError object
   * following RFC 7807 Problem Details format. This ensures consistent
   * error handling across the application.
   *
   * MIGRATION NOTE: Replaces the legacy DNN Try-Catch pattern:
   * ```vb
   * ' Legacy VB.NET
   * Try
   *   ' Data operation
   * Catch ex As Exception
   *   ' Log to EventLog
   *   Throw
   * End Try
   * ```
   *
   * @param error - HttpErrorResponse from failed HTTP request
   * @returns Observable<never> - Observable that immediately emits the ApiError
   *
   * Error Status Code Mapping (from Section 0.7.6):
   * - 400 Bad Request: ValidationException → Return validation errors
   * - 401 Unauthorized: UnauthorizedException → Return auth required
   * - 403 Forbidden: ForbiddenException → Return access denied
   * - 404 Not Found: NotFoundException → Return entity not found
   * - 500 Internal Server Error: Unhandled Exception → Return generic error
   */
  private handleError(error: HttpErrorResponse): Observable<never> {
    let apiError: ApiError;

    if (error.error && this.isApiError(error.error)) {
      // Backend returned a structured RFC 7807 error response
      apiError = error.error as ApiError;
    } else if (error.status === 0) {
      // Network error or CORS issue - no response from server
      apiError = {
        type: 'https://dnnmigration.com/errors/network',
        title: 'Network Error',
        status: 0,
        detail: 'Unable to connect to the server. Please check your network connection and try again.'
      };
    } else if (error.status === 401) {
      // Unauthorized - authentication required
      apiError = {
        type: 'https://dnnmigration.com/errors/unauthorized',
        title: 'Unauthorized',
        status: 401,
        detail: 'Authentication is required to access this resource. Please log in and try again.'
      };
    } else if (error.status === 403) {
      // Forbidden - insufficient permissions
      apiError = {
        type: 'https://dnnmigration.com/errors/forbidden',
        title: 'Forbidden',
        status: 403,
        detail: 'You do not have permission to perform this action.'
      };
    } else if (error.status === 404) {
      // Not Found - resource doesn't exist
      apiError = {
        type: 'https://dnnmigration.com/errors/not-found',
        title: 'Not Found',
        status: 404,
        detail: 'The requested resource could not be found.'
      };
    } else if (error.status === 409) {
      // Conflict - resource state conflict
      apiError = {
        type: 'https://dnnmigration.com/errors/conflict',
        title: 'Conflict',
        status: 409,
        detail: 'The request could not be completed due to a conflict with the current state of the resource.'
      };
    } else if (error.status === 422) {
      // Unprocessable Entity - validation failed
      apiError = {
        type: 'https://dnnmigration.com/errors/validation',
        title: 'Validation Error',
        status: 422,
        detail: 'The request contains invalid data. Please check your input and try again.'
      };
    } else if (error.status >= 500) {
      // Server error
      apiError = {
        type: 'https://dnnmigration.com/errors/server-error',
        title: 'Server Error',
        status: error.status,
        detail: 'An unexpected error occurred on the server. Please try again later.'
      };
    } else {
      // Generic error for other status codes
      apiError = {
        type: 'https://dnnmigration.com/errors/unknown',
        title: 'Error',
        status: error.status,
        detail: error.message || 'An unexpected error occurred.'
      };
    }

    // Log error for debugging in development
    if (!environment.production) {
      console.error('[ApiService] HTTP Error:', {
        status: error.status,
        statusText: error.statusText,
        url: error.url,
        error: apiError
      });
    }

    return throwError(() => apiError);
  }

  /**
   * Type guard to check if an error object conforms to the ApiError interface.
   *
   * @param error - The error object to validate
   * @returns True if the error object has all required ApiError properties
   */
  private isApiError(error: unknown): error is ApiError {
    if (typeof error !== 'object' || error === null) {
      return false;
    }

    const candidate = error as Record<string, unknown>;

    return (
      typeof candidate['type'] === 'string' &&
      typeof candidate['title'] === 'string' &&
      typeof candidate['status'] === 'number' &&
      typeof candidate['detail'] === 'string'
    );
  }
}
