// MIGRATION: Net-new integration-test infrastructure. The legacy DotNetNuke 4.x solution shipped no
// automated test host — verification was manual against the ASP.NET Web Forms UI. This fixture boots
// the migrated ASP.NET Core 8 BFF (DnnMigration.Api) fully in-process via WebApplicationFactory<Program>
// and, for deterministic and infrastructure-free runs, swaps two production concerns:
//   1. the EF Core SQL Server DnnDbContext  -> an EF Core InMemory database (no external SQL Server), and
//   2. the JWT bearer authentication        -> a test AuthenticationHandler that authenticates a
//                                              synthetic administrator principal, so the class-level
//                                              [Authorize] on the CRUD controllers is satisfied without a
//                                              real login / BCrypt round-trip.
// It is the linchpin of Validation Gate 5: PortalApiTests, ModuleApiTests and UserApiTests share a single
// instance per test class via IClassFixture<CustomWebApplicationFactory>.
using System.Security.Claims;
using System.Text.Encodings.Web;
using DnnMigration.Infrastructure.Data;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.TestHost;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace DnnMigration.IntegrationTests;

/// <summary>
/// An xUnit shared test fixture that bootstraps the entire <c>DnnMigration.Api</c> host in-memory for
/// integration testing. It derives from <see cref="WebApplicationFactory{TEntryPoint}"/> using the API's
/// global-namespace <c>Program</c> entry type, then overrides the composed service graph so that tests run
/// against an isolated EF Core InMemory store and a permissive test authentication scheme instead of the
/// production SQL Server database and JWT bearer pipeline.
/// </summary>
/// <remarks>
/// <para>
/// Consumed by <c>PortalApiTests</c>, <c>ModuleApiTests</c> and <c>UserApiTests</c> through
/// <c>IClassFixture&lt;CustomWebApplicationFactory&gt;</c>. Each test class receives one factory instance,
/// and therefore one uniquely named InMemory database, keeping the classes isolated from one another while
/// sharing state across the requests within a single class.
/// </para>
/// <para>
/// The InMemory provider honours the entities' <c>ValueGeneratedOnAdd()</c> integer primary keys
/// (PortalID / ModuleID / UserID), so a <c>POST</c> returns a server-assigned identifier that the tests
/// read back from the response envelope to drive the rest of the CRUD lifecycle.
/// </para>
/// </remarks>
public class CustomWebApplicationFactory : WebApplicationFactory<Program>
{
    /// <summary>
    /// The name of the test authentication scheme. Registered as the default scheme so that the
    /// application's default authorization policy (<c>RequireAuthenticatedUser</c>) resolves against
    /// <see cref="TestAuthHandler"/> and every <c>[Authorize]</c> CRUD endpoint authenticates deterministically.
    /// </summary>
    public const string TestScheme = "Test";

    // MIGRATION: A unique InMemory database name per factory instance. Because xUnit creates one fixture
    // per test class (IClassFixture), each class gets a fully isolated store; scopes created within a single
    // factory resolve the SAME store because the InMemory provider keys databases by name.
    private readonly string _databaseName = "IntegrationTests_" + Guid.NewGuid().ToString("N");

    /// <summary>
    /// Reconfigures the web host after the application's own service registration has run, replacing the
    /// production database provider and authentication scheme with test doubles.
    /// </summary>
    /// <param name="builder">The web host builder supplied by <see cref="WebApplicationFactory{TEntryPoint}"/>.</param>
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        // MIGRATION: force Development so HSTS is not applied (the test client speaks plain HTTP) and
        // detailed error responses are enabled. Program.cs only calls UseHsts() when NOT in Development,
        // and never calls UseHttpsRedirection, so CRUD requests are never redirected.
        builder.UseEnvironment("Development");

        // ConfigureTestServices runs AFTER the application's ConfigureServices, so the removals and
        // re-registrations below reliably override the host's production wiring.
        builder.ConfigureTestServices(services =>
        {
            RemoveDbContextRegistrations(services);

            // MIGRATION: replace SQL Server with an isolated InMemory store. ValueGeneratedOnAdd integer
            // primary keys are auto-generated by the InMemory provider, so POSTs return server-assigned ids.
            services.AddDbContext<DnnDbContext>(options => options.UseInMemoryDatabase(_databaseName));

            // MIGRATION: replace JWT bearer with a test handler registered as the DEFAULT scheme. Because
            // this AddAuthentication(TestScheme) runs last (in ConfigureTestServices), its
            // Configure<AuthenticationOptions> setting DefaultScheme = "Test" wins over the app's "Bearer"
            // default, so the default authorization policy authenticates via the "Test" scheme. The app's
            // JWT handler registration is intentionally left intact — overriding the default scheme suffices.
            services.AddAuthentication(TestScheme)
                .AddScheme<AuthenticationSchemeOptions, TestAuthHandler>(TestScheme, _ => { });
        });
    }

    /// <summary>
    /// Removes the application's SQL Server <see cref="DnnDbContext"/> wiring from the service collection so
    /// the InMemory provider can take over cleanly, preventing EF Core's "more than one database provider"
    /// error. Removing the <see cref="DbContextOptions{TContext}"/> descriptor is the essential step; the
    /// additional removals are defensive and safe.
    /// </summary>
    /// <param name="services">The service collection being reconfigured for the test host.</param>
    private static void RemoveDbContextRegistrations(IServiceCollection services)
    {
        var descriptorsToRemove = services.Where(d =>
            d.ServiceType == typeof(DbContextOptions<DnnDbContext>) ||
            d.ServiceType == typeof(DbContextOptions) ||
            d.ServiceType == typeof(DnnDbContext) ||
            (d.ServiceType.IsGenericType &&
             d.ServiceType.GetGenericTypeDefinition() == typeof(DbContextOptions<>) &&
             d.ServiceType.GenericTypeArguments.Length == 1 &&
             d.ServiceType.GenericTypeArguments[0] == typeof(DnnDbContext)))
            .ToList();

        foreach (var descriptor in descriptorsToRemove)
        {
            services.Remove(descriptor);
        }
    }

    /// <summary>
    /// Creates a service scope, ensures the InMemory store is freshly (re)created, optionally seeds it via
    /// the supplied delegate, and persists the changes. Accessing <see cref="WebApplicationFactory{TEntryPoint}.Services"/>
    /// triggers the host build lazily.
    /// </summary>
    /// <param name="seed">
    /// An optional asynchronous callback that receives the scoped <see cref="DnnDbContext"/> and adds any
    /// pre-existing rows a test requires. When <c>null</c>, the store is simply reset to empty.
    /// </param>
    /// <returns>A task that completes once the store has been reset, seeded, and saved.</returns>
    /// <remarks>
    /// The mandatory CRUD-lifecycle tests are self-contained via <c>POST</c> and do not need seeding; this
    /// helper exists for optional GET-list / seed scenarios and keeps the fixture reusable.
    /// </remarks>
    public async Task ResetAndSeedAsync(Func<DnnDbContext, Task>? seed = null)
    {
        using var scope = Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<DnnDbContext>();
        await db.Database.EnsureDeletedAsync();
        await db.Database.EnsureCreatedAsync();
        if (seed is not null)
        {
            await seed(db);
            await db.SaveChangesAsync();
        }
    }
}

/// <summary>
/// A test <see cref="AuthenticationHandler{TOptions}"/> that, by default, authenticates a synthetic HOST
/// (super-user) administrator principal. Registered by <see cref="CustomWebApplicationFactory"/> as the
/// default authentication scheme so that the resource controllers' authorization policy is satisfied
/// without a real login / token-issuance flow.
/// </summary>
/// <remarks>
/// <para>
/// MIGRATION: this replaces DotNetNuke's Forms Authentication / <c>PortalSecurity</c> DES-based identity for
/// the purpose of testing. It uses the .NET 8 three-argument base constructor
/// <c>(IOptionsMonitor&lt;AuthenticationSchemeOptions&gt;, ILoggerFactory, UrlEncoder)</c>; the legacy
/// four-argument overload that also took <c>ISystemClock</c> is <c>[Obsolete]</c> in .NET 8 and would fail
/// the Gate 1 warnings-as-errors build.
/// </para>
/// <para>
/// The DEFAULT identity is a host/super user (<c>isSuperUser=true</c>, role <c>Administrators</c>,
/// <c>portalId=0</c>). Emitting a host identity by default means the per-portal authorization guards added
/// for the resource controllers (Issue #1) are bypassed for the pre-existing CRUD tests, which use a
/// server-assigned portal id — so those tests remain green without modification.
/// </para>
/// <para>
/// To drive the negative/positive authorization tests, a request may override the synthetic identity with
/// these test-only headers (honoured ONLY by this in-process test handler — they do not exist in production):
/// <list type="bullet">
///   <item><description><c>X-Test-Anonymous: true</c> — authenticate nothing (<see cref="AuthenticateResult.NoResult"/>), so authorization challenges with 401 (the "no token" case).</description></item>
///   <item><description><c>X-Test-Roles</c> — a comma-separated role list; the literal <c>none</c> (or an empty value) yields a caller with NO roles (the insufficient-privilege case).</description></item>
///   <item><description><c>X-Test-PortalId</c> — the caller's <c>portalId</c> claim (for cross-portal tests).</description></item>
///   <item><description><c>X-Test-IsSuperUser</c> — <c>true</c>/<c>false</c>; set <c>false</c> to exercise the non-host portal-scoping path.</description></item>
/// </list>
/// The claim shape (<c>portalId</c>, <c>isSuperUser</c>, <see cref="ClaimTypes.Role"/>, <see cref="ClaimTypes.Name"/>)
/// matches how <c>JwtTokenService</c> issues real tokens, so authorization resolves identically under test and in production.
/// </para>
/// </remarks>
public class TestAuthHandler : AuthenticationHandler<AuthenticationSchemeOptions>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="TestAuthHandler"/> class using the .NET 8 three-argument
    /// base constructor (no obsolete <c>ISystemClock</c> parameter).
    /// </summary>
    /// <param name="options">Monitor for the scheme options.</param>
    /// <param name="logger">The logger factory used by the base handler.</param>
    /// <param name="encoder">The URL encoder used by the base handler.</param>
    public TestAuthHandler(
        IOptionsMonitor<AuthenticationSchemeOptions> options,
        ILoggerFactory logger,
        UrlEncoder encoder)
        : base(options, logger, encoder)
    {
    }

    /// <summary>
    /// Builds and returns an authentication result. By default the principal is a synthetic host/super
    /// administrator; the identity's claims can be overridden per request via the <c>X-Test-*</c> headers
    /// documented on the class, and <c>X-Test-Anonymous</c> suppresses authentication entirely.
    /// </summary>
    /// <returns>A completed task with the resulting <see cref="AuthenticateResult"/>.</returns>
    /// <remarks>
    /// Returns synchronously via <see cref="Task.FromResult{TResult}(TResult)"/> (no <c>async</c> keyword) so
    /// no CS1998 warning is raised. The <c>Role</c> and <c>Name</c> claim types match the API's JWT setup
    /// (<see cref="ClaimTypes.Role"/> / <see cref="ClaimTypes.Name"/>), and the custom <c>portalId</c> /
    /// <c>isSuperUser</c> claims match <c>JwtTokenService</c>, keeping authorization resolution identical to
    /// production for any endpoint or policy that inspects them.
    /// </remarks>
    protected override Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        // Test-only override: simulate an unauthenticated (no-token) request so the framework's
        // authorization pipeline challenges with 401. Reproduces the "no/invalid token -> 401" contract
        // that the negative authorization tests assert.
        if (HeaderEquals("X-Test-Anonymous", "true"))
        {
            return Task.FromResult(AuthenticateResult.NoResult());
        }

        // Resolve each claim from its X-Test-* override when present, else fall back to the default
        // host/super administrator identity. For roles, header PRESENCE (even empty, or the literal
        // "none") dictates the exact role set, so a test can produce a caller with NO roles.
        string roles;
        if (Request.Headers.TryGetValue("X-Test-Roles", out var rolesHeader))
        {
            var raw = rolesHeader.ToString();
            roles = string.Equals(raw, "none", StringComparison.OrdinalIgnoreCase) ? string.Empty : raw;
        }
        else
        {
            roles = "Administrators";
        }

        var portalId = Request.Headers.TryGetValue("X-Test-PortalId", out var portalHeader)
            ? portalHeader.ToString()
            : "0";
        var isSuperUser = Request.Headers.TryGetValue("X-Test-IsSuperUser", out var superHeader)
            ? superHeader.ToString()
            : "true";

        var claims = new List<Claim>
        {
            new(ClaimTypes.NameIdentifier, "1"),
            new(ClaimTypes.Name, "test.admin"),
            new(ClaimTypes.Email, "test.admin@dnnmigration.local"),
            new("portalId", portalId),
            new("isSuperUser", isSuperUser)
        };

        foreach (var role in roles.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            claims.Add(new Claim(ClaimTypes.Role, role));
        }

        var identity = new ClaimsIdentity(claims, CustomWebApplicationFactory.TestScheme);
        var principal = new ClaimsPrincipal(identity);
        var ticket = new AuthenticationTicket(principal, CustomWebApplicationFactory.TestScheme);
        return Task.FromResult(AuthenticateResult.Success(ticket));
    }

    /// <summary>
    /// Returns <see langword="true"/> when the named request header is present and equals
    /// <paramref name="value"/> (case-insensitive). Used to detect the test-only control headers.
    /// </summary>
    private bool HeaderEquals(string name, string value)
        => Request.Headers.TryGetValue(name, out var headerValue)
           && string.Equals(headerValue.ToString(), value, StringComparison.OrdinalIgnoreCase);
}
