// MIGRATION: [AAP Gate 5 — API Integration Tests] ModulesController CRUD integration test. Second of the three
// mandatory Gate-5 resource controllers (Portal / Module / User). It proves the Module CRUD status-code contract
// (POST -> 201, GET -> 200, PUT -> 200, DELETE -> 204) end-to-end through the real Program.cs pipeline over an
// EF Core InMemory store, PLUS the three Module-specific behaviors the shared ModuleCrudTests does not cover:
//   1. the portal-scoped list requires a [FromQuery, BindRequired] portalId — omitting it is a 400 (the canonical
//      [ApiController] model-binding 400, independent of FluentValidation);
//   2. SOFT delete — a deleted module disappears from the ?portalId= list. ModuleService.DeleteAsync sets
//      IsDeleted = true and TabId = null (legacy ModuleController.vb DeleteTabModule L852 "objModule.IsDeleted =
//      True"), and ModuleRepository.GetByPortalPagedAsync filters !IsDeleted, so the row is excluded from the list;
//   3. GET /api/modules/{id} for a non-existent id returns 404 (still requires the ?portalId= query).
// Source lineage: legacy Library/Components/Modules/ModuleController.vb (soft-delete via objModule.IsDeleted = True)
// and Website/admin/Modules/ModuleSettings.ascx.vb (module settings / lifecycle).
//
// MIGRATION: [CP4 review — Test Isolation] CustomWebApplicationFactory now exposes the centralized ResetAndSeed hook
// (EnsureDeleted -> EnsureCreated -> seed), so each test RESETS the shared InMemory store to empty and then seeds a
// fresh Portal -> Tab before acting. Portal and Tab integer keys are store-generated by EF convention (and honored by
// the InMemory provider). Because every test starts from a known-empty database, the per-portal list assertions can
// assert EXACT counts. xUnit parallelization is disabled assembly-wide (AssemblyInfo.cs), so the tests run sequentially.
//
// MIGRATION: The seeded Test principal (TestAuthHandler) is a host SuperUser, so it bypasses
// ApiControllerBase.EnforceTenant for any portalId — the Gate-5 status codes are exercised without minting a real
// JWT. Every Module endpoint (GET-by-id, PUT, DELETE) is portal-scoped and requires the ?portalId= query parameter.

using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using DnnMigration.Application.DTOs.Module;
using DnnMigration.Domain.Entities;
using DnnMigration.Infrastructure.Data;
using FluentAssertions;
using Xunit;

namespace DnnMigration.IntegrationTests.ApiTests;

[Trait("Category", "Integration")]
public sealed class ModulesControllerTests : IClassFixture<CustomWebApplicationFactory>
{
    // MIGRATION: Web (camelCase, case-insensitive) options PLUS a JsonStringEnumConverter. ModuleResponse.ControlType
    // is a SecurityAccessLevel enum; the API configures no AddJsonOptions converter, so it currently serializes enums
    // as numbers. The converter reads BOTH numbers and string names, keeping response deserialization robust either
    // way. Request DTOs carry no enum members, so serialization is unaffected.
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        Converters = { new JsonStringEnumConverter() }
    };

    private readonly CustomWebApplicationFactory _factory;
    private readonly HttpClient _client;

    public ModulesControllerTests(CustomWebApplicationFactory factory)
    {
        _factory = factory;
        _client = factory.CreateClient();
    }

    // ----- helpers ------------------------------------------------------------------------------------------------

    // MIGRATION: [CP4 review — Test Isolation] Multi-tenant seeding (AAP 0.7.1) now RESETS first via the centralized
    // CustomWebApplicationFactory.ResetAndSeed (EnsureDeleted -> EnsureCreated -> seed), so each test starts from a
    // known-empty store. A Module is scoped by PortalId and placed on a TabId, so a Portal is seeded first (its
    // store-generated PortalId is read back) and then a Tab in that portal (its store-generated TabId is read back).
    // Explicit primary-key values are never set — EF convention generates the int keys on SaveChanges and the InMemory
    // provider honors that, yielding a deterministic (portalId, tabId) pair per test from the freshly reset database.
    private (int PortalId, int TabId) SeedPortalAndTab()
    {
        var portalId = 0;
        var tabId = 0;

        _factory.ResetAndSeed(db =>
        {
            var portal = new Portal { PortalName = "Seed Portal" };
            db.Portals.Add(portal);
            db.SaveChanges();

            var tab = new Tab { PortalId = portal.PortalId, TabName = "Seed Tab" };
            db.Tabs.Add(tab);
            db.SaveChanges();

            portalId = portal.PortalId;
            tabId = tab.TabId;
        });

        return (portalId, tabId);
    }

    // MIGRATION: POSTs the minimal VALID create body and returns the created ModuleResponse. CreateModuleValidator
    // requires PortalId >= 0, TabId >= 0 and ModuleDefId (NotNull + GreaterThan(0)); ModuleDefId = 1 satisfies that
    // rule (omitting it is the QA-1 Module 400). Border is left null so the single-digit Border rule does not apply.
    private static async Task<ModuleResponse> CreateModuleAsync(HttpClient client, int portalId, int tabId)
    {
        var response = await client.PostAsJsonAsync(
            "/api/modules",
            new CreateModuleRequest { PortalId = portalId, TabId = tabId, ModuleDefId = 1, ModuleTitle = "Test Module" },
            JsonOptions);

        response.StatusCode.Should().Be(HttpStatusCode.Created);

        var envelope = await response.Content.ReadFromJsonAsync<DataEnvelope<ModuleResponse>>(JsonOptions);
        envelope.Should().NotBeNull();
        envelope!.Data.Should().NotBeNull();
        return envelope.Data!;
    }

    // ----- tests --------------------------------------------------------------------------------------------------

    [Fact]
    [Trait("Category", "Integration")]
    public async Task Post_Module_Returns201Created()
    {
        var (portalId, tabId) = SeedPortalAndTab();

        var response = await _client.PostAsJsonAsync(
            "/api/modules",
            new CreateModuleRequest { PortalId = portalId, TabId = tabId, ModuleDefId = 1, ModuleTitle = "Test Module" },
            JsonOptions);

        response.StatusCode.Should().Be(HttpStatusCode.Created);
        response.Headers.Location.Should().NotBeNull("HandleCreated emits a CreatedAtAction Location header");

        var envelope = await response.Content.ReadFromJsonAsync<DataEnvelope<ModuleResponse>>(JsonOptions);
        envelope.Should().NotBeNull();
        envelope!.Data.Should().NotBeNull();
        envelope.Data!.ModuleId.Should().HaveValue();
        envelope.Data.ModuleId.GetValueOrDefault().Should()
            .BeGreaterThan(0, "ValueGeneratedOnAdd assigns the InMemory store key on insert");
        envelope.Data.ModuleTitle.Should().Be("Test Module");
        envelope.Data.PortalId.Should().Be(portalId);
    }

    [Fact]
    [Trait("Category", "Integration")]
    public async Task Get_Module_ById_Returns200()
    {
        var (portalId, tabId) = SeedPortalAndTab();
        var created = await CreateModuleAsync(_client, portalId, tabId);
        var moduleId = created.ModuleId.GetValueOrDefault();

        // MIGRATION: GET-by-id is portal-scoped — portalId is a BindRequired query parameter.
        var response = await _client.GetAsync($"/api/modules/{moduleId}?portalId={portalId}");

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var envelope = await response.Content.ReadFromJsonAsync<DataEnvelope<ModuleResponse>>(JsonOptions);
        envelope.Should().NotBeNull();
        envelope!.Data.Should().NotBeNull();
        envelope.Data!.ModuleId.Should().Be(moduleId);
    }

    [Fact]
    [Trait("Category", "Integration")]
    public async Task Put_Module_Returns200()
    {
        var (portalId, tabId) = SeedPortalAndTab();
        var created = await CreateModuleAsync(_client, portalId, tabId);
        var moduleId = created.ModuleId.GetValueOrDefault();

        // MIGRATION: UpdateModuleValidator requires only TabId >= 0 (Border optional, no PortalId). PUT is
        // portal-scoped — the route id is authoritative and portalId is the BindRequired query parameter.
        var response = await _client.PutAsJsonAsync(
            $"/api/modules/{moduleId}?portalId={portalId}",
            new UpdateModuleRequest { TabId = tabId, ModuleTitle = "Updated Module" },
            JsonOptions);

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var envelope = await response.Content.ReadFromJsonAsync<DataEnvelope<ModuleResponse>>(JsonOptions);
        envelope.Should().NotBeNull();
        envelope!.Data.Should().NotBeNull();
        envelope.Data!.ModuleTitle.Should().Be("Updated Module");
    }

    [Fact]
    [Trait("Category", "Integration")]
    public async Task Delete_Module_Returns204()
    {
        var (portalId, tabId) = SeedPortalAndTab();
        var created = await CreateModuleAsync(_client, portalId, tabId);
        var moduleId = created.ModuleId.GetValueOrDefault();

        var response = await _client.DeleteAsync($"/api/modules/{moduleId}?portalId={portalId}");

        response.StatusCode.Should().Be(HttpStatusCode.NoContent);
    }

    [Fact]
    [Trait("Category", "Integration")]
    public async Task Delete_Module_SoftDelete_ExcludedFromPortalList()
    {
        var (portalId, tabId) = SeedPortalAndTab();
        var created = await CreateModuleAsync(_client, portalId, tabId);
        var deletedId = created.ModuleId.GetValueOrDefault();

        var deleteResponse = await _client.DeleteAsync($"/api/modules/{deletedId}?portalId={portalId}");
        deleteResponse.StatusCode.Should().Be(HttpStatusCode.NoContent);

        // MIGRATION: soft delete is proven through the LIST, not GET-by-id. DeleteAsync sets IsDeleted = true (and
        // TabId = null) but retains PortalId, and GetByIdAsync does NOT filter IsDeleted — so a GET by id would still
        // return 200. Only GetByPortalPagedAsync filters !IsDeleted, so the deleted module is excluded here. This is
        // the canonical soft-delete assertion.
        var listResponse = await _client.GetAsync($"/api/modules?portalId={portalId}&pageIndex=0&pageSize=50");
        listResponse.StatusCode.Should().Be(HttpStatusCode.OK);

        var envelope = await listResponse.Content.ReadFromJsonAsync<PagedEnvelope<ModuleResponse>>(JsonOptions);
        envelope.Should().NotBeNull();
        envelope!.Data.Should().NotBeNull();

        // MIGRATION: [CP4 review — Test Isolation] From the known state (exactly one created module, then soft-deleted)
        // the portal-scoped list is now EMPTY: the single module is excluded, so the page is empty and totalCount=0.
        envelope.Data!.Should().BeEmpty();
        envelope.Data.Should().NotContain(
            m => m.ModuleId == deletedId,
            "a soft-deleted module is excluded from the portal-scoped list");
        envelope.Meta.Should().NotBeNull();
        envelope.Meta!.TotalCount.Should().Be(0);
    }

    [Fact]
    [Trait("Category", "Integration")]
    public async Task Get_Modules_List_MissingPortalId_Returns400()
    {
        // MIGRATION: portalId is [FromQuery, BindRequired] on GetByPortal; omitting it triggers the [ApiController]
        // automatic 400 at model binding (guaranteed, independent of FluentValidation). No seeding required.
        var response = await _client.GetAsync("/api/modules");

        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
    }

    [Fact]
    [Trait("Category", "Integration")]
    public async Task Get_Module_ById_NotFound_Returns404()
    {
        var (portalId, _) = SeedPortalAndTab();

        // MIGRATION: portalId is BindRequired on GET-by-id too, so it MUST be supplied — otherwise this would be a
        // 400 (model binding), not the 404 under test. Module 999999 never exists (store keys start at 1 and
        // increment), so the portal-scoped lookup returns null -> Result.Failure -> HandleGet -> 404.
        var response = await _client.GetAsync($"/api/modules/999999?portalId={portalId}");

        response.StatusCode.Should().Be(HttpStatusCode.NotFound);

        // MIGRATION: [CP4 review — Test Coverage] Assert the EXACT RFC 7807 problem-detail message the migrated
        // ModuleService emits. The message is intentionally opaque (it does NOT echo the requested id).
        var problem = await EnvelopeReader.ReadProblemDetailAsync(response);
        problem.Status.Should().Be(404);
        problem.Title.Should().Be("Not Found");
        problem.Detail.Should().Be("The requested module was not found.");
    }

    [Fact]
    [Trait("Category", "Integration")]
    public async Task Get_Modules_List_Returns200Paged()
    {
        var (portalId, tabId) = SeedPortalAndTab();
        var created = await CreateModuleAsync(_client, portalId, tabId);
        var moduleId = created.ModuleId.GetValueOrDefault();

        const int pageSize = 50;
        var response = await _client.GetAsync($"/api/modules?portalId={portalId}&pageIndex=0&pageSize={pageSize}");

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var envelope = await response.Content.ReadFromJsonAsync<PagedEnvelope<ModuleResponse>>(JsonOptions);
        envelope.Should().NotBeNull();
        envelope!.Data.Should().NotBeNull();

        // MIGRATION: [CP4 review — Envelope Contract + Test Isolation] After reset + seed (one portal/tab) + exactly
        // one created module, assert the EXACT paged metadata from the known state (totalCount=1 at pageIndex=0 /
        // pageSize=50, a single total page, no previous/next page) and that the single page holds only that module.
        envelope.Data!.Should().ContainSingle().Which.ModuleId.Should().Be(moduleId);
        envelope.Meta.Should().NotBeNull();
        envelope.Meta!.TotalCount.Should().Be(1);
        envelope.Meta.PageIndex.Should().Be(0);
        envelope.Meta.PageSize.Should().Be(pageSize);
        envelope.Meta.TotalPages.Should().Be(1);
        envelope.Meta.HasPreviousPage.Should().BeFalse();
        envelope.Meta.HasNextPage.Should().BeFalse();
    }

    // ----- private deserialization envelopes ----------------------------------------------------------------------

    // MIGRATION: Minimal typed views of the API's standard success envelopes (ApiControllerBase). The single-value
    // envelope is { data, meta }; the paged envelope is { data: [...], meta: { totalCount, pageIndex, ... } }. These
    // are PRIVATE NESTED records so they can never collide with the equivalently-shaped helpers in the sibling
    // Portal/User controller test files. Unmatched JSON members (e.g. the empty single-value "meta") are ignored by
    // System.Text.Json; positional parameters bind case-insensitively to the camelCase response keys (Web defaults).
    private sealed record DataEnvelope<T>(T? Data);

    private sealed record PagedEnvelope<T>(List<T>? Data, PagedMeta? Meta);

    private sealed record PagedMeta(
        int TotalCount,
        int PageIndex,
        int PageSize,
        int TotalPages,
        bool HasPreviousPage,
        bool HasNextPage);
}
