using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using DnnMigration.Domain.Entities;

namespace DnnMigration.Infrastructure.Persistence.Configurations;

// MIGRATION: EF Core 8 Fluent API mapping for the physical [UserPortals] membership table, replacing the
// legacy ADO.NET / SqlDataProvider stored-procedure layer (GetUserPortals / AddUserPortal) together with the
// reflection-based CBO.FillObject hydration. Per ADR-002 the existing DotNetNuke 4.9.0.85 schema is mapped
// UNCHANGED: no migrations, no schema generation, no EnsureCreated, no data migration.
//
// [UserPortals] is the physical home of the user-to-portal association that the legacy flattened UserInfo
// denormalized onto its PortalID property and that CP2 UserConfiguration therefore Ignore()s on the User
// entity (the [Users] table has no PortalID column). Mapping this table here lets UserRepository JOIN
// [Users] -> [UserPortals] to resolve portal-scoped user queries without filtering the ignored User.PortalID.
//
// MIGRATION (casing): the [UserPortals] DDL declares the key/columns with a lowercase 'd' (UserId, PortalId,
// UserPortalId). The CLR properties keep the DNN-conventional UserID/PortalID/UserPortalID casing and are
// remapped to the physical column names with HasColumnName - the same casing-drift correction CP2
// UserConfiguration applies for AffiliateID -> AffiliateId.

/// <summary>
/// Entity Framework Core configuration that maps the <see cref="UserPortal"/> POCO entity onto the
/// pre-existing, unchanged DotNetNuke <c>dbo.UserPortals</c> table, including its composite primary key and
/// the lowercase-d physical column names.
/// </summary>
/// <remarks>
/// <para>
/// The class is discovered automatically by <c>DnnDbContext.OnModelCreating</c> through
/// <c>ModelBuilder.ApplyConfigurationsFromAssembly</c>. No relationship navigations are configured: the
/// repository joins <c>[Users]</c> to <c>[UserPortals]</c> explicitly by user id, so no inverse collection is
/// added to <see cref="User"/> and no cascade path is introduced.
/// </para>
/// <para>
/// Schema-fidelity rules (ADR-002): the table and column names are preserved verbatim (with the casing
/// remap), the composite key (<c>UserId</c>, <c>PortalId</c>) is declared via <c>HasKey</c>, and no
/// SQL-Server-specific defaults, computed columns, or raw SQL are configured so the model builds cleanly
/// against <c>Microsoft.EntityFrameworkCore.InMemory</c> as well as SQL Server. The surrogate
/// <c>UserPortalId</c> IDENTITY column is mapped as an ordinary property (it is not part of the key); within
/// the current scope this entity is queried read-only, so no value-generation configuration is required.
/// </para>
/// </remarks>
public sealed class UserPortalConfiguration : IEntityTypeConfiguration<UserPortal>
{
    /// <summary>
    /// Configures the <see cref="UserPortal"/> entity against the physical <c>dbo.UserPortals</c> table.
    /// </summary>
    /// <param name="builder">The builder used to configure the <see cref="UserPortal"/> entity type.</param>
    public void Configure(EntityTypeBuilder<UserPortal> builder)
    {
        // Physical table: dbo.UserPortals (CREATE TABLE in DotNetNuke.Schema.SqlDataProvider). Schema-
        // qualified and named verbatim per ADR-002 - the table already exists and must not be regenerated.
        builder.ToTable("UserPortals", "dbo");

        // Composite primary key: PK CLUSTERED ([UserId], [PortalId]) per the [UserPortals] DDL. Composite key
        // parts are NOT treated as store-generated by EF convention, matching the schema (the values are
        // supplied; the surrogate UserPortalId is the IDENTITY column).
        builder.HasKey(up => new { up.UserID, up.PortalID });

        // --- The real, physical [UserPortals] columns (mapped verbatim from the schema DDL, lowercase-d casing) ---
        builder.Property(up => up.UserID).HasColumnName("UserId");                  // [UserId]       int      NOT NULL  (composite PK)
        builder.Property(up => up.PortalID).HasColumnName("PortalId");              // [PortalId]     int      NOT NULL  (composite PK)
        builder.Property(up => up.UserPortalID).HasColumnName("UserPortalId");      // [UserPortalId] int      NOT NULL IDENTITY(1,1) (surrogate, not in key)
        builder.Property(up => up.CreatedDate).HasColumnName("CreatedDate");        // [CreatedDate]  datetime NOT NULL
        builder.Property(up => up.Authorised).HasColumnName("Authorised");          // [Authorised]   bit      NOT NULL
    }
}
